# image will be published to ghcr.io/<user>/<name>
#name: startingleaf
# description will be included in the image's metadata
#description: Custom operating system image based on Secureblue and Fedora Atomic Desktops, built with BlueBuild. 
# the base image to build on top of (FROM) and the version tag to use
#base-image: ghcr.io/secureblue/silverblue-main-hardened
#image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:

  # Copies files from the repo into the image
  - type: files
    files:
      - source: system
        destination: /

  # Signs image with sigstore
  - type: signing

  # Installs chezmoi and (in theory) automatically imports dotfiles
  - type: chezmoi
    repository: "https://github.com/oakleafknight06/dotfiles"

  - type: rpm-ostree
    repos:
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://copr.fedorainfracloud.org/coprs/trixieua/morewaita-icon-theme/repo/fedora-%OS_VERSION%/trixieua-morewaita-icon-theme-fedora-%OS_VERSION%.repo
      - https://repository.mullvad.net/rpm/stable/mullvad.repo
    install:
      - tailscale
      - fish # Fish shell. Not set as login, executed with terminal emulator
      - sg3_utils # Enables Apple SuperDrive udev rule
      - morewaita-icon-theme # Icon theme that adds icons for additional mimetypes and folders, as well as adwaita-style icons for third-party apps.
      - adw-gtk3-theme # Consistent styling for GTK3 apps
      - ibus-rime # Better Chiense input
      - mullvad-vpn
    remove:
      # Unneeded / legacy GNOME apps removed
      - gnome-system-monitor
      - gnome-shell-extension-launch-new-instance
      - gnome-shell-extension-window-list
      - gnome-classic-session 
      - gnome-tweaks
      - gnome-software

  - type: systemd
    system:
      enabled:
        - tailscaled
        - mullvad-daemon
 
  - type: fonts
    fonts:
      nerd-fonts:
        - AdwaitaMono
        - IntelOneMono
        - JetBrainsMono
      google-fonts:
        - Roboto

  - type: gnome-extensions
    install:
      - Tiling Assistant
      - Mullvad Indicator

  - type: gschema-overrides # test & compile override files in config/gschema-overrides/
    include:
      - zz1-startingleaf.gschema.override
      - zz1-tilingassistant.gschema.override
