# image will be published to ghcr.io/<user>/<name>
name: startingleaf
# description will be included in the image's metadata
description: Custom operating system image based on BlueBuild and Fedora Silverblue. 
# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
                  #
                  # copies config/files/usr into your image's /usr
                  #
                  # configuration you wish to end up in /etc/ on the booted system
                  # should be added into /usr/etc/ as that is the proper "distro"
                  # config directory on ostree. Read more in the files module's README

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/pesader/showmethekey/repo/fedora-%OS_VERSION%/pesader-showmethekey-fedora-%OS_VERSION%.repo
      - https://repository.mullvad.net/rpm/stable/mullvad.repo
      - https://copr.fedorainfracloud.org/coprs/dusansimic/themes/repo/fedora-%OS_VERSION%/dusansimic-themes-fedora-%OS_VERSION%.repo
    install:
      - starship
      - showmethekey
      - mullvad-vpn
      - morewaita-icon-theme
      - adw-gtk3-theme
      - fish
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
    optfix:
      - Mullvad VPN # This is the directory being fixed, not the package name

  - type: yafti

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - IntelOneMono
        - JetBrainsMono
      google-fonts:
        - Roboto

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
 
  - type: systemd
    system:
      enabled:
        - mullvad-daemon

  - type: gschema-overrides
    include:
      - zz1-startingleaf.gschema.override # test & compile the override file included in config/gschema-overrides/zz1-myoverride.gschema.override
